### ISSUE TITLE
emoji.wpf.TextBlock textwrapping not working

### ISSUE THREAD

**Issue by Dev-Reynz** [samhocevar/emoji.wpf#10]
Textwrapping is working fine with text but not in emoji.

![untitled](https://user-images.githubusercontent.com/30256318/49775924-f0825480-fd34-11e8-9178-a4ca5b29eee5.png)

`<emoji:TextBlock
                                                        MaxWidth="500"
                                                        Margin="5"
                                                        VerticalAlignment="Center"
                                                        customTextBlock:HyperService.Text="{Binding Text, Converter={StaticResource decodeStringConverter}}"
                                                        FontSize="14"
                                                        FontWeight="Normal"
                                                        LineHeight="20"
                                                        TextWrapping="Wrap"/>`

**Comment by samhocevar** [comment]
It should now work properly; see the sample application:

![wrapping](https://user-images.githubusercontent.com/245089/98687416-fd1ce680-2369-11eb-9b63-0a65f0fbfd07.gif)
