### ISSUE TITLE
emoji:RichTextBox Input content Error

### ISSUE THREAD

**Issue by yanjinhuagood** [samhocevar/emoji.wpf#14]
Sdk: .net framework 4.6.1
 <emoji:RichTextBox FontSize="24" Margin="5"/>

Managed Debugging Assistant "FatalExecution EngineError"

Message = Managed Debugging Assistant "FatalExecution EngineError": "Error encountered at runtime. The wrong address is 0x67d2623f, on thread 0x58d4. The error code is 0x80131623. This error may be a bug in the CLR, or a bug in the unsafe or non-verifiable part of user code. Common sources of this bug include user marshaling errors on COM-interop or PInvoke that can damage the stack."
@samhocevar Thanks

**Comment by samhocevar** [comment]
This bug is caused by asserts in the Undo stack handler for `RichTextBox`. There is no easy way to fix it, so unfortunately I had to disable Undo in the latest version. Ctrl-Z will be back when I have found a proper solution.

**Comment by yanjinhuagood** [comment]
well. thank you

**Comment by samhocevar** [comment]
Hello! I wanted to warn you that the next version of Emoji.Wpf will bump the minimal .NET Framework version from 3.0 to 4.0, which makes the crash disappear, and I have thus reactivated Undo support and Ctrl-Z.

**Comment by yanjinhuagood** [comment]
powerful👍 well. thank you
