### ISSUE TITLE
Emoji:RichTextBox selection does not give text including emoji.

### ISSUE THREAD

**Issue by ervishal89** [samhocevar/emoji.wpf#19]
Hi, 

In Sample app, RichTextBox.SelectAll() and RichTextBox.Selection.Text does not show all text with emoji.

Please advise.

**Comment by samhocevar** [comment]
Unfortunately, the RichTextBox implementation is very buggy. I haven't managed to get selection or undo/redo to work properly yet.

**Comment by samhocevar** [comment]
FYI this is now fixed in e5bd5b05648553311faa0fdda0f94452de69dede. `SelectAll()` and `Selection.Text` now work as expected.

As a shortcut, you can also use `RichTextBox.Text` directly.
