### ISSUE TITLE
In RichTextBox, can not use other input method except microsoft pinyin

### ISSUE THREAD

**Issue by FunJoo** [samhocevar/emoji.wpf#20]
![image](https://user-images.githubusercontent.com/30665751/75857916-190ed680-5e32-11ea-81f6-1a5bef9a89e6.png)
When I use ms pinyin input method, I can input sth in RichTextBox. 
But using 3rd party input method can not input anything, even using US keyboard - English.
my xaml:
<emoji:RichTextBox x:Name="TextBoxDoc"
                           Grid.Row="1"
                           Margin="5"
                           AcceptsReturn="True"
                           VerticalScrollBarVisibility="Visible"
                           FontSize="15"/>

**Comment by samhocevar** [comment]
Can you please let me know if this still happens with version 0.2.0? Thanks!

**Comment by FunJoo** [comment]
It's all right now in v0.2.0
