### ISSUE TITLE
Add emoji to textBox from PickerEmoji

### ISSUE THREAD

**Issue by DeLuca92** [samhocevar/emoji.wpf#22]
How i add the from the picker to my textBox?

**Comment by babakmdi** [comment]
private void mypicker_SelectionChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            var emoji = mypicker.Selection;
             Textbox.Text = Textbox.Text + emoji ; }

**Comment by samhocevar** [comment]
I think babakmdi’s proposal is quite fine, so I’m closing this issue. Please reopen if you have any trouble with the solution.

**Comment by samhocevar** [comment]
Note that you can now subscribe to the `EmojiPicker.Picked` event, which makes things even easier.

See the [new Sample.cs code](https://github.com/samhocevar/emoji.wpf/blob/02f59523e44ca8ce77e6cb92aa6efee77edd0243/Sample/Sample.xaml.cs#L43):

```c#
    EmojiPicker.Picked += (o, e) =>
        EmojiRichTextBox.CaretPosition.InsertTextInRun(e.Emoji);
```
