### ISSUE TITLE
Selection changed only fires once

### ISSUE THREAD

**Issue by r-work** [samhocevar/emoji.wpf#25]
if you select X emoji, SelectionChanged fires, if you open the picker again click the same emoji, it closes without firing SelectionChanged, this sort of makes sense as you're selecting the same emoji, but that becomes an issue if you're using the SelectionChanged to insert selected emojis into the RichTextBox.

**Comment by samhocevar** [comment]
Thanks for the suggestion! What do you think about this new event?
```c#
public event EmojiPickedEventHandler Picked;
```

Usage example:

```c#
EmojiPicker.Picked += (o, e) =>
    EmojiRichTextBox.CaretPosition.InsertTextInRun(e.Emoji);
```

**Comment by r-work** [comment]
Just tried it, works great, thank you!
