### ISSUE TITLE
System.InvalidOperationException occurs when using WindowsKey+. to input an emoji

### ISSUE THREAD

**Issue by bbuerger** [samhocevar/emoji.wpf#26]
When using the Windows 10 emoji picker to input an emoji the sample crashes with the following exception:

System.InvalidOperationException
  HResult=0x80131509
  Message=Es ist kein "CultureInfo" mit "IetfLanguageTag 'ug'" vorhanden.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

Inner Exception 1:
ArgumentException: Der Kulturname "ug" wird nicht unterstützt.
Parametername: name

**Comment by samhocevar** [comment]
Thanks for reporting this. It appears that the crash is no longer present when Emoji.Wpf is built with a slightly more recent of .NET Framework (4.0), so I think the next release will just use that one.

**Comment by samhocevar** [comment]
Can you please confirm that the crash goes away for you with the code currently on `master`? Thanks!

**Comment by samhocevar** [comment]
I believe this is fixed in version 0.2.0.
