### ISSUE TITLE
Add flags

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/emoji.wpf#29]
The Segoe UI Emoji font does not provide flags, but here is how we could add flag support.

 - choose a repository of SVG flags such as [this one](https://github.com/hampusborgos/country-flags)
 - convert SVG to XAML using _e.g._ [SvgToXaml](https://github.com/BerndK/SvgToXaml)
 - embed the XAML inside Emoji.Wpf
 - at render time, skip glyph rendering and directly return the DrawImage from the XAML; add a 2-pixel black border to mimic the Windows Emoji style

One drawback is that some flags are insanely detailed, which is unreasonable for drawings that we will render at sizes of about 20 pixels. For instance [El Salvador](https://emojipedia.org/flag-el-salvador/):

![image](https://user-images.githubusercontent.com/245089/106572853-3fa12a00-6539-11eb-9e18-78c70cdec377.png)

Bonus: using Inkscape’s “Envelope Deformation” path effect it is possible to distort any SVG to create a wavy flag such as in 🏳‍🌈:

![image](https://user-images.githubusercontent.com/245089/106572189-6ad74980-6538-11eb-8b4f-dfa15abbbb8d.png)

**Comment by virzak** [comment]
Have you considered https://github.com/googlefonts/noto-emoji ?

![image](https://user-images.githubusercontent.com/6209775/110174557-489e4900-7dce-11eb-8045-2f63e024a3c7.png)

It should in theory allow you to just add some lines here:

https://github.com/samhocevar/emoji.wpf/blob/cf61720705edaf0ed10647526caa084c42555e5a/Emoji.Wpf/Internal/OpenTypeFont.cs#L112

**Comment by samhocevar** [comment]
Unfortunately that font provides bitmap glyphs; I would like, if possible, to keep vector rendering even for flags. I am making progress with mass-converting vector flag data to proper XAML but I’m running into a lot of corner cases so it’s not ready yet.

Note that the vector source for Noto Emoji flags is roughly the same as the one I am using (see the El Salvador flag in their repository, for instance: https://github.com/googlefonts/noto-emoji/blob/main/third_party/region-flags/svg/SV.svg)

**Comment by samhocevar** [comment]
Apparently https://openmoji.org/ provides SVG flags. That can be pretty interesting.

**Comment by CoelWu** [comment]
What about twitter's emoji? That might be a good option too.
See this for a reference: https://github.com/twitter/twemoji

**Comment by samhocevar** [comment]
Thanks @CoelWu, that’s a good reference, too. Unfortunately they have rounded corners and I fear that I would have to retouch them manually…

**Comment by samhocevar** [comment]
On the plus side, my automatic warping of the Openmoji SVG flags is starting to look good. These are SVG documents that I just need to convert to XAML now:

<img src="https://user-images.githubusercontent.com/245089/110243108-41f00d00-7f59-11eb-8336-66a43ec23318.png" width=400/>
<img src="https://user-images.githubusercontent.com/245089/110243122-5207ec80-7f59-11eb-9e03-6bac659a7398.png" width=400/>
<img src="https://user-images.githubusercontent.com/245089/110243160-7fed3100-7f59-11eb-8071-ce46987d8042.png" width=400/>
<img src="https://user-images.githubusercontent.com/245089/110243250-dd817d80-7f59-11eb-84a5-76fab6bc3726.png" width=400/>

**Comment by CoelWu** [comment]
> On the plus side, my automatic warping of the Openmoji SVG flags is starting to look good. These are SVG documents that I just need to convert to XAML now:
> 
> <img alt="" width="400/" src="https://user-images.githubusercontent.com/245089/110243108-41f00d00-7f59-11eb-8336-66a43ec23318.png">
> 
> <img alt="" width="400/" src="https://user-images.githubusercontent.com/245089/110243122-5207ec80-7f59-11eb-9e03-6bac659a7398.png">
> 
> <img alt="" width="400/" src="https://user-images.githubusercontent.com/245089/110243160-7fed3100-7f59-11eb-8071-ce46987d8042.png">
> 
> <img alt="" width="400/" src="https://user-images.githubusercontent.com/245089/110243250-dd817d80-7f59-11eb-84a5-76fab6bc3726.png">

Might be better if the black border of the floags were removed? They look pretty wired I think.

**Comment by samhocevar** [comment]
Yes, the idea is to be consistent with the rest of the Windows emoji and the other flags, something like this: https://github.com/samhocevar/emoji.wpf/blob/flags/flag-template.svg

**Comment by samhocevar** [comment]
Things are going pretty well. This is pure SVG, with the Windows emoji font for comparison.

![image](https://user-images.githubusercontent.com/245089/110255844-22c3a080-7f96-11eb-8de8-3e4d7a83c63b.png)

![image](https://user-images.githubusercontent.com/245089/110255746-91542e80-7f95-11eb-97c7-4292ccea58f3.png)

**Comment by samhocevar** [comment]
Almost there. SVG converted to XAML, now I just need to resize and position the flag, and finally add the outline and pole overlays.

![image](https://user-images.githubusercontent.com/245089/110537235-b3c78280-8122-11eb-88de-80a421a39383.png)

**Comment by samhocevar** [comment]
Merged in `main`. Needs some polishing and optimisation, but the base feature is here.

![image](https://user-images.githubusercontent.com/245089/110711817-71747300-8200-11eb-8a21-a975018cfe8f.png)

![image](https://user-images.githubusercontent.com/245089/110711853-85b87000-8200-11eb-8d2d-62ee3a13d1e3.png)

**Comment by zm-cttae** [comment]
Is it feasible to export this work as a TTF so people can hack it into Windows? This is amazing!

**Comment by daflame899** [comment]
> Is it feasible to export this work as a TTF so people can hack it into Windows? This is amazing!

Would be awesome if it could

**Comment by Frendiks24** [comment]
Please redesign the emojis.

![Image](https://github.com/user-attachments/assets/f0dbf8f0-5129-477b-b62e-a8937dcb551e)

**Comment by Frendiks24** [comment]
Please redesign the emojis as the fluent, 3D ones in Windows 11.

**Comment by Chasmical** [comment]
@zm-cttae I think so. I've exported the flags from Twemoji's color font (rectangular, rounded), and put them in Segoe UI Emoji's tables, so it has all of the vanilla Win11 emojis + flags. It should be possible to do the same with any other SVG font.
https://github.com/Chasmical/flag-emojis-for-windows
