### ISSUE TITLE
Warning Emoji.Wpf may not be fully compatible with '.NET 5.0'

### ISSUE THREAD

**Issue by SJGowen** [samhocevar/emoji.wpf#36]
I have used Emoji.Wpf to give my application that displays emoji's colour! My application is using the latest dot net core framework and I am just using the standard animal emoji's. When I add the Emoji.Wpf nuget package I get the below warning!

Package 'Emoji.Wpf 0.2.5' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.

Despite this, the application seems to be behaving properly! Below I have pasted my applications csproj file in case it gives you any clues:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Emoji.Wpf" Version="0.2.5" />
  </ItemGroup>

</Project>
```

**Comment by samhocevar** [comment]
I believe this is the same as #24 and will be fixed in the next release, which is happening very soon!

By the way, if you would like to, you can post a screenshot of your application in #37 and add a link to it!

**Comment by samhocevar** [comment]
This should be fixed in Emoji.Wpf 0.3.0!
