### ISSUE TITLE
Bad quality at low resolutions

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/emoji.wpf#4]
Text is very blurry at small sizes, because the glyph rendering method does not appear to benefit from hinting. But experiments indicate that better rendering is possible just by tweaking the glyph positions.

Another option would be to downscale pre-rendered bitmaps instead of drawing small glyph sizes.

**Comment by samhocevar** [comment]
Update: pre-rendered bitmaps seem to have improved the rendering somewhat.

**Comment by TheKeytrap** [comment]
@samhocevar Do you have an example of a solution yet ?

**Comment by samhocevar** [comment]
@TheKeytrap I improved supersampling and bitmap caching in version 0.0.16 (relevant commits were 427d35c0d56ec10f448c32d8d51c95f8ba1c294b and 1a55d813a5d7904a592e81e820302c1ea989d815). Do you still suffer from low quality rendering? If so, can you please post screenshots maybe?

**Comment by samhocevar** [comment]
@varKeytrap since version 0.2.3, Emoji.Wpf uses vector rendering at all sizes; the blurriness caused by bitmap scaling has disappeared. I’m therefore closing this bug.
