### ISSUE TITLE
Richtextbox append unexpected behavior 

### ISSUE THREAD

**Issue by ghost** [samhocevar/emoji.wpf#41]
If you try to append emoji from emoji picker to wpf:richtextbox when it already includes numbers. some extra emoji will replace the actual text

The code I use to append to richtextbox :
`       private void Picker_Picked(object sender, Emoji.Wpf.EmojiPickedEventArgs e)
        {
            richtextbox.AppendText(e.Emoji);
        }
`
steps:

before append :
![image](https://user-images.githubusercontent.com/44848120/115106141-5cfe6580-9f78-11eb-8dd7-cabcd4f9b550.png)

expected behavior when appending ☺️ emoji for example
![image](https://user-images.githubusercontent.com/44848120/115106191-959e3f00-9f78-11eb-865f-8e750d883d22.png)

result:
![image](https://user-images.githubusercontent.com/44848120/115106218-bf576600-9f78-11eb-9990-f6858bc1fca4.png)

running system:
Windows 10 1909
.NET 5
WPF

**Comment by samhocevar** [comment]
Hi! This was fixed some time ago in Emoji.Wpf v0.3.4. I am sorry, I missed this bug and forgot to follow up.
