### ISSUE TITLE
Numbers are overwritten from emoji

### ISSUE THREAD

**Issue by dinos19** [samhocevar/emoji.wpf#43]
When i insert numbers and then pick an emoji from picker it overwrites my numbers with the selected emoji *n where "n" is the number of numbers where inserted in text before selection. Maybe im doing something wrong , tried txtMessage.Text = txtMessage.Text + e.Emoji; and txtMessage.CaretPosition.InsertTextInRun(e.Emoji);
               txtMessage.Focus();
               txtMessage.CaretPosition = txtMessage.Document.ContentEnd;
same result.

**Comment by samhocevar** [comment]
What widget are you using? Is this `emoji:RichTextBox`?

**Comment by dinos19** [comment]
yes, user is typing his msg on richtextbox

**Comment by samhocevar** [comment]
Hi! Sorry about the delay. This is fixed in Emoji.Wpf 0.3.4.
