### ISSUE TITLE
CopyingHandler OnCopy method in RichTextBox does not work as expected

### ISSUE THREAD

**Issue by arnobpl** [samhocevar/emoji.wpf#5]
I have tried your repository. Thank you for your great effort! I have checked the CopyingHandler in RichTextBox. But it doesn't work as expected regardless of the selection. It just copies space characters of the number of selected characters. Anyways I have solved the issue internally. If you wish, I can provide you the modified code. :) Though my code is not well-optimized, but it just works as expected.

**Comment by samhocevar** [comment]
Thanks for the report. `RichTextBox` is not very well designed for now, only `TextBlock` is in a reasonably good shape. I would be happy to have a look at your code.

**Comment by arnobpl** [comment]
Feel free to let me know if any further change is necessary to fix the issue! :)

**Comment by NeilBurkholder** [comment]
I'm came up with this solution:

     protected void OnCopy(object o, DataObjectCopyingEventArgs e)
    {
        string clipboard = "";

        for (TextPointer p = MsgViewer.Selection.Start, next = null;
                p != null && p.CompareTo(MsgViewer.Selection.End) < 0;
                p = next)
        {
            next = p.GetNextInsertionPosition(LogicalDirection.Forward);
            if (next == null)
                break;

            var t = new TextRange(p, next);
            var emoji = (next.Parent as Run)?.PreviousInline as Emoji.Wpf.EmojiInline;
            if ((p.Parent as Run).PreviousInline != emoji && emoji != null) clipboard += emoji?.Text;
            else clipboard += t.Text;
        }

        Clipboard.SetText(clipboard);
        e.Handled = true;
        e.CancelCommand();
    }

**Comment by samhocevar** [comment]
Thank you for your contributions and your patience. After lots of inaction and a lot of reading, too, I finally found a more elegant solution to this problem.

**Comment by samhocevar** [comment]
I closed this issue some time ago, but I just wanted to let you know copy/paste support has been greatly improved in the current `master` branch, and Undo/Redo now works properly, too.
