### ISSUE TITLE
Copying all digits are replaced into emoji

### ISSUE THREAD

**Issue by arturbipolar** [samhocevar/emoji.wpf#57]
Test text :   Button_22wawae 
I insert an emoji
Result : Button_😗wawae😗

**Comment by ClonkAndre** [comment]
Same problem here

**Comment by samhocevar** [comment]
Are you using the NuGet package or a more recent version from GitHub?

**Comment by ClonkAndre** [comment]
@samhocevar Could you update the NuGet package please? That would be really nice

**Comment by samhocevar** [comment]
Hi! I believe this is finally fixed in emoji.wpf 0.3.4, available on NuGet. Can you please confirm?

**Comment by ClonkAndre** [comment]
Looks like it's working! This is awesome! Thank you very much for updating the NuGet Package! 🤠

**Comment by samhocevar** [comment]
Thanks for notifying!
