### ISSUE TITLE
Emojis will sometimes get placed in random places

### ISSUE THREAD

**Issue by ClonkAndre** [samhocevar/emoji.wpf#59]
I'm using the TwitterAPI to get the text from tweets on Twitter but the emojis are quite often not placed correctly with the Emoji.Wpf.RichTextBox.

### Examples

**Original text on twitter**
**1**: Please no 50/50 😅
**2**: Which of those 2 names do you like more?
**3**: https://t.co/RhTFG1jjDr

**Here is how it looks like when i print it via Console.WriteLine**
**1**: Please no 50/50 ??
**2**: Which of those 2 names do you like more?
**3**: https://t.co/RhTFG1jjDr

**And this is how it shows up in the Emoji.Wpf.RichTextBox**
**1**: Please no 😅/😅 😅
**2**: Which of those 👀names do you like more?
**3**: https://t.co/RhTFG😅jDr

**Comment by samhocevar** [comment]
I’m sorry about this bug, it was actually fixed in 2021 (same as #43 #45 #50), but there hadn’t been a new release until a few months ago. Version 0.3.4 should no longer have this problem.
