### ISSUE TITLE
How to apply for c# winforms

### ISSUE THREAD

**Issue by googlecomvn** [samhocevar/emoji.wpf#60]
Brilliant project
How to customize to support for c# winforms app

**Comment by samhocevar** [comment]
Unfortunately this library is only for WPF. I would suggest migrating to WPF or a more modern toolkit.

However you may have some success embedding a WPF control inside your WinForms app, for instance:

 - https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/walkthrough-creating-new-wpf-content-on-windows-forms-at-design-time?view=netframeworkdesktop-4.8
 - https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.integration.elementhost?redirectedfrom=MSDN&view=windowsdesktop-7.0
