### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by TrabacchinLuigi** [samhocevar/emoji.wpf#62]
Sometimes while clicking on the control i receive a null reference exception, which isn't handled and crash the entire process

**Comment by SpitzerCharles** [comment]
This could be due to a missing null-check fixed in commit `ab26608413038674df730b564042e4a57dc43109` (currently available only on the `feature/bbcode` branch)

**Comment by TrabacchinLuigi** [comment]
Any chance that will be merged before the entire feature ?

**Comment by samhocevar** [comment]
Definitely! I kinda missed that fix, it makes sense, thanks for reporting the issue.

**Comment by samhocevar** [comment]
Yes! I would like to deal with a few Windows 11 regressions first but if I can't manage it in the next couple of days I'll do a release.

**Comment by samhocevar** [comment]
Hi! This is fixed in emoji.wpf 0.3.4, available on NuGet.
