### ISSUE TITLE
Can support TextBox？

### ISSUE THREAD

**Issue by cmfGit** [samhocevar/emoji.wpf#9]

**Comment by samhocevar** [comment]
Unfortunately, `TextBox` seems too complicated to support. I believe I will only support `RichTextBox`.

**Comment by cmfGit** [comment]
I want to limit the length of the content and get the Text content. The RichtextBox doesn't seem to support it

**Comment by samhocevar** [comment]
You may try to support `MaxLength` in a `RichTextBox` using the following method, based on [this StackOverflow answer](https://stackoverflow.com/a/51876926/111461):

  - listen to the `PreviewKeyDown` event
  - if the text is at the maximum length, mark the event as handled and return

To improve on the above code, you may use  `MapVirtualKey` (see [this other answer](https://stackoverflow.com/a/3639366/111461)) to check whether the key is a printable character or not.

**Comment by cmfGit** [comment]
This is such a great idea，Thank you！
